<a href="https://colab.research.google.com/github/Saurabhgupta1qz/100days-ML/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.array(5)
print(a)
a.ndim

5


0

In [ ]:
arr = np.array([1,2,34,5,5])
print(arr)
arr.ndim

[ 1  2 34  5  5]


1

In [ ]:
arr = np.array([[1,23,3],[23,45,56],[23,4,5]])
print(arr)
arr.ndim

[[ 1 23  3]
 [23 45 56]
 [23  4  5]]


2

In [ ]:
tensor3 = np.array([[[1,2,3],[3,4,5]],[[1,2,5],[6,7,8]]])
tensor3.ndim

3